{
    'name': 'Odoo Whatsapp Base',
    'version': '1.0.',
    'author': 'TechUltra Solutions',
    'category': 'Base',
    'live_test_url': 'https://www.techultrasolutions.com/blog/news-2/odoo-whatsapp-integration-a-boon-for-business-communication-25',
    'website': 'www.techultrasolutions.com',
    'price': 9.0,
    'currency': 'USD',
    'summary': 'Whatsapp base, Whatsapp All in one module to connect the whatsapp api with odoo.',
    'description': """Whatsapp base module and all in one whatsapp module is to connect the chat api with whatsapp and odoo this is the standard module which require to setup the other modules.
        """,
    'depends': ['base', 'mail'],
    'data': [
        'security/whatsapp_security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/wa_template.xml',
        'wizard/wa_compose_message_view.xml',
        'views/res_config_settings_views.xml',
        'views/provider.xml',
        'views/res_users.xml',
        'views/channel_provider_line.xml',
        'views/res_partner.xml',
        'views/whatsapp_history.xml',
        'views/wa_template.xml',
        'views/variables.xml',
        'views/components.xml',
        'views/mail_channel.xml',
        'views/mail_message.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'images': ['static/description/banner.jpg'],
    # 'post_init_hook': '_set_image_in_company',
}
